name: Run main.py once
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Install apturl
        run: |
          sudo apt-get update
          sudo apt-get install -y apturl
          sudo apt-get install -y brltty
      - name: Update pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run main script
        env:
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
          TOKEN: ${{secrets.TOKEN}}
          TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
        run: |
          python3 main.py
